name: CD-Liara

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm install
          npm run build --if-present
          npm i @liara/cli@3
          liara deploy --app="music-pwa-api" --api-token="$LIARA_TOKEN" --detach
