name: CD-Liara

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: update-liara
      - env: 
          region: iran
        run: |
          npm i -g @liara/cli@3
          liara deploy --app="music-pwa-api" --api-token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2M2I2MWJmMWYzZDM5N2M1NzgyNDNjZTUiLCJpYXQiOjE2NzQzNjQ2OTF9.EnEH3quPAEP47VLzUL7pz71XjvMNk3fvhJZqm2Rw_h4" --detach
